version: '3.8'
services:
  my_r_service:
    build: .
    environment:
      DISABLE_AUTH: "true"
      ROOT: "true"
      PASSWORD: "1234"
    ports:
      - "127.0.0.1:8787:8787"
    volumes:
      - .:/home/rstudio